name: Build iOS Dylib

on:
  push:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Theos and SDKs (Bypass API Rate Limit)
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          git clone https://github.com/theos/sdks.git ~/theos/sdks
          echo "THEOS=~/theos" >> $GITHUB_ENV

      - name: Build Dylib
        run: |
          make clean
          make
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HaiCuong_ModMenu_Dylib
          path: .theos/obj/debug/*.dylib
